### ISSUE TITLE
failure fired in logstash-input-azure_blob_storage

### ISSUE THREAD

**Issue by penut1234** [janmg/logstash-input-azure_blob_storage#37]
There are errors fired when I tried to use logstash-input-azure_blob_storage, can you help to check what is the root cause of the error? 

e5114ca4f761df81d8b9b82a00be457_0.log from 5873 to 150695
[ERROR] 2023-05-04 05:20:12.860 [[logstash_3]<azure_blob_storage] javapipeline - A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:logstash_3
  Plugin: <LogStash::Inputs::AzureBlobStorage container=>"###-####-aks-####", codec=><LogStash::Codecs::Line id=>"line_47cba90b-c584-4aa7-9835-####", enable_metric=>true, charset=>"UTF-8", delimiter=>"\n">, logtype=>"raw", prefix=>"logs/####", storageaccount=>"####", access_key=><password>, interval=>300, id=>"####", debug_until=>1000, addfilename=>true, registry_path=>"elk_registry_data/registry_container_logs.dat", enable_metric=>true, dns_suffix=>"core.windows.net", registry_create_policy=>"resume", addall=>false, debug_timer=>false, skip_learning=>false, file_head=>"{\"records\":[", file_tail=>"]}", path_filters=>["**/*"]>
  Error: InvalidBlobType (409): The blob type is invalid for this operation.
RequestId:88bf8c47-f01e-000c-0648-####
Time:2023-05-04T05:20:12.8424899Z
  Exception: Azure::Core::Http::HTTPError
  Stack: /usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/azure-storage-common-2.0.4/lib/azure/core/http/http_request.rb:154:in `call'
org/jruby/RubyMethod.java:116:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/azure-storage-common-2.0.4/lib/azure/core/http/signer_filter.rb:28:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/azure-storage-common-2.0.4/lib/azure/core/http/http_request.rb:111:in `block in call'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/azure-storage-common-2.0.4/lib/azure/core/service.rb:36:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/azure-storage-common-2.0.4/lib/azure/core/filtered_service.rb:34:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/azure-storage-common-2.0.4/lib/azure/core/signed_service.rb:41:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/azure-storage-common-2.0.4/lib/azure/storage/common/service/storage_service.rb:60:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/azure-storage-blob-2.0.3/lib/azure/storage/blob/blob_service.rb:179:in `call'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/azure-storage-blob-2.0.3/lib/azure/storage/blob/block.rb:276:in `list_blob_blocks'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-input-azure_blob_storage-0.12.7/lib/logstash/inputs/azure_blob_storage.rb:413:in `partial_read'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-input-azure_blob_storage-0.12.7/lib/logstash/inputs/azure_blob_storage.rb:271:in `block in run'
org/jruby/RubyHash.java:1519:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-input-azure_blob_storage-0.12.7/lib/logstash/inputs/azure_blob_storage.rb:246:in `run'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:414:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:405:in `block in start_input'
[INFO ] 2023-05-04 05:20:14.062 [[logstash_3]<azure_blob_storage] azureblobstorage - resuming from remote registry elk_registry_data/registry_container_logs.dat

**Comment by penut1234** [comment]
The plugin version is:  logstash-input-azure_blob_storage (0.12.7)

**Comment by penut1234** [comment]
The plugin configurations:

    input {
        azure_blob_storage {
            storageaccount => "####"
            container => "####"
            prefix => "logs/Containers"
            access_key => "####=="
            debug_until => 1000
            interval => 300
            logtype => raw
            codec => line
            addfilename => true
            registry_path => 'registry_container_logs.dat'
        }
    }
    
    output {
        loki {
        url => "https://####/loki/api/v1/push"
        username => "#####"
        password => '#####='
        batch_size => 112640
        retries => 5
        min_delay => 3
        max_delay => 5
      }
    }

**Comment by janmg** [comment]
The error happens during a partial read. That means that the file has grown in the last 300 seconds and wasn't zero bytes before. This plugin assumes that it's a BlockBlob, it's not designed with PageBlobs or AppendBlobs in mind. They may work, but not when they grow. Archived blobs are ignored, because those can not be read.

It would be great if you can isolate the file that caused this issue. If you know the know you can check the properties with the storage explorer the tool or in the azure portal.

**Comment by janmg** [comment]
I think this is the same issue as 36. If I'm correct, setting the head and tail to an empty string may work. I'd like to close this issue and work on 36 if you agree

**Comment by penut1234** [comment]
sure and thanks for your support.

**Comment by janmg** [comment]
I have finally pushed 0.12.9 would be great if you can test it out in a test environment, because I know it probably works but haven't done extensive testing. In the configs you can add "append => true" to signal you expect an appendblob, but if you don't I'll catch the exception and set the parameter anyway.
