### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by sree0744** [janmg/logstash-input-azure_blob_storage#38]
Getting below error 

[ERROR] 2023-05-25 04:22:59.725 [[main]<azure_blob_storage] json - JSON parse error, original data now in message field {:error=>#<LogStash::Json::ParserError: Illegal unquoted character ((CTRL-CHAR, code 27)): has to be escaped using backslash to be included in string value

The error seems to be ESC CHAR in the original input log file.Would it be possible for this plugin to have a parameter to ignore this error and forward the logs to filter plugin

**Comment by janmg** [comment]
I can add an optional switch to sanitize the input, so that the parser doesn't choke. That could happen around line 274 if @is_json and cleanjson filter through the stream.

I'm struggling to find the time to implement this thing and the issue 36 regarding append blobs. But I'll do it when I have a free moment

**Comment by sree0744** [comment]
Thanks. In our pipeline run, could see below log entry and it is this stage for more than 2 hours. Is this because of invalid Json in the input file
[INFO ] 2023-05-26 07:26:32.985 [[main]<azure_blob_storage] azureblobstorage - worklist contains 1430 blobs

We didn't got any additional traces, so could you please help to know any ways to identify the issue.

**Comment by janmg** [comment]
I pushed version 0.12.9. It does have a cleanjson, but it's only valid for the json_lines codec. It could be implemented also for json.  It would require converting bytes to strings before putting the event in the queue and this string needs to be encoded first, it's already done by the codec. I think the below line will cleanup the json, but it will take me some time to implement and test it. Pushing out 0.12.9 was already a bigger job than I hoped for.

lines.chars.select(&:valid_encoding?).join
