### ISSUE TITLE
Not able to ship Azure Activity Logs to Graylog / ELK

### ISSUE THREAD

**Issue by neeleshg** [janmg/logstash-input-azure_blob_storage#39]
Hi
I am not able to push Azure Activity Logs to Graylog and Elastic as well.
I am using Logstash 8.7.1 version along with gelf output using docker-compose.
Here is my configuration file of Logstash:
```
input {
     azure_blob_storage {
          connection_string => "DefaultEndpointsProtocol=https;AccountName=<BLOB_NAME>;AccountKey=<BLOB_ACCOUNT_KEY>;EndpointSuffix=core.usgovcloudapi.net"
         container => "insights-activity-logs"
         registry_create_policy => "start_over"
         codec => "json"
         addall => true
         path_filters => ['**/*.json']
         addfilename => true
         prefix => "resourceId=/"
         # Possible options: `do_not_break`, `with_head_tail`, `without_head_tail`
         interval => 5
     }
 }

filter {
    json {
        source => "message"
    }
    mutate {
        add_field => {"short_message" => "This is short message"}
        add_field => { "host" => "127.0.0.1" }
        #remove_field => [ "message" ]
    }
    date {
        match => ["unixtimestamp", "UNIX"]
    }
}

output {
    gelf {
        host => "127.0.0.1"
        port => 12201
    }
    stdout {
      codec => rubydebug {metadata => true}
    }
}```

Now I am seeing the Messages in `stdout`, however it is not pushing logs to gelfudp output.

I am getting  below error:
`ArgumentError: short_message is missing. Options version, short_message and host must be set.` 
What should be ideal config for Azure Activity Logs?

**Comment by janmg** [comment]
This is the input plugin. The error message you get is from the output plugin. Gelf is not something I know about. The configuration is documented here
https://www.elastic.co/guide/en/logstash/current/plugins-outputs-gelf.html#plugins-outputs-gelf-short_message

What I see from you're configuration is that you set host, but the error message also states that you need "version, short_message and host"
maybe you need to feed the message into the short_message option short_message => "%{message}" or this has to do with the ship_metadata and ignore_metadata.

But if it's not related to the input side, I'm closing the ticket here

**Comment by neeleshg** [comment]
Thanks @janmg for response.
I changed some config as you mentioned, now short_message error gone, still not able to push logs to Graylog..
Checking with Golf now..
However for Azure Activity logs, how should I configure input plugin and set filters in Logstash?

**Comment by neeleshg** [comment]
Got it work now..
Somehow not able to push messages to Gelf UDP.. but it is working with Gelf TCP.
Also fixed short_message error by adding value as array.
```
filter {
    json {
        source => "records"
    }
    mutate {
        add_field => {"short_message" => ["Azure Activity Logs"]}
        add_field => { "host" => "logstash" }
    }
    date {
        match => ["unixtimestamp", "UNIX"]
    }
}
```

**Comment by neeleshg** [comment]
Now I am able to send Azure Activity Logs to Graylog.
I had to configure Gelf TCP Output in Logstash and Gelf TCP Input in Graylog.
