### ISSUE TITLE
No filename when using line codec (and extra "\r" character at the end of every line)

### ISSUE THREAD

**Issue by abhijit-sahay** [janmg/logstash-input-azure_blob_storage#46]
Thank you for this very nice plug-in.  I am trying to use it for CSV files by using the "line" codec but each line gets an extra "\r" character at the end of every line, e.g. see the event.original field below -

Also - is there a way to capture the path and name of the source file within its container as a field in the event?

```
{
  "@timestamp": [
    "2023-12-04T22:31:16.452Z"
  ],
  "@version": [
    "1"
  ],
  "data_stream.dataset": [
    "generic"
  ],
  "data_stream.namespace": [
    "default"
  ],
  "data_stream.type": [
    "logs"
  ],
  "event.original": [
    "37,1,,0,0,0,0,BILLING,,Email,0,0,0,2022-03-31 03:22:29.990\r"
  ],
  "message": [
    "37,1,,0,0,0,0,BILLING,,Email,0,0,0,2022-03-31 03:22:29.990\r"
  ],
  "_id": "X8j1NowBpjArVxS9BV6_",
  "_index": ".ds-logs-generic-default-2023.12.04-000001",
  "_score": null
}
```

**Comment by janmg** [comment]
The \r symbolizes the carriage return. A windows ascii text file contains a line feed and a carriage return, I believe you can set the end of line delimiter inside the codec configuration
codec => line {
    delimiter => "\r\n"
}

You can add the filename by setting addfilename to true
addfilename => true

Beware that the plugin has issues working with the more recent versions of logstash. I am working on a replacement to read events using a standalone golang program that can feed into logstash. It will take me a lot of time to write and will be initially for nsgflowlogs.

**Comment by abhijit-sahay** [comment]
Thank you! I was able to solve the delimiter problem but still cannot see the filename in Kibana.  Do I need to change any other setting? I am using this config now (to capture mulitple text line blocks separated by blank lines.)

```
input {
    azure_blob_storage {
        storageaccount => "xx"
        access_key => "yy"
        container => "logs"
        addfilename => true
        codec => multiline {
            pattern => "^\r$"
            negate => true
            what => "next"
        }
        registry_create_policy => "start_over"
    }
}

```

**Comment by janmg** [comment]
that addfilename looks correct. Kibana learns which values exist in the output and if you add new fields you have to go to management and refresh the index patterns

**Comment by abhijit-sahay** [comment]
After some struggle I figured out that addfilename works if (and only if) there is no "codec".  Unfortunately, the files I am dealing with are all unstructured multi-line text log files, so I guess I will just have to live without it.  Thank you again for your kind help.

**Comment by janmg** [comment]
I pushed 0.12.10 which adds the addfilename to non json files. Your analysis helped me find the spot where to add the 3 lines, but I can't easily test it, so let me know if it works and close the issue if it does.

**Comment by abhijit-sahay** [comment]
I can confirm that addfilename works correctly now.   Thank you.
