### ISSUE TITLE
Write file and log is not align

### ISSUE THREAD

**Issue by royoan** [janmg/logstash-input-azure_blob_storage#6]
The logstash logs show:
`[2020-05-15T04:46:47,790][INFO ][logstash.inputs.azureblobstorage][nsg] nsg partial file resourceId=/SUBSCRIPTIONS/XXX.../BASTION-SG/y=2020/m=05/d=15/h=04/m=00/macAddress=XXXXXXXEF06/PT1H.json from 75184 to 76751
[2020-05-15T04:46:47,846][INFO ][logstash.inputs.azureblobstorage][nsg] nsg processed 1711 events, saving 714 blobs and offsets to registry data/registry.dat
[2020-05-15T04:47:33,197][INFO ][logstash.inputs.azureblobstorage][nsg] nsg processed 2564 events, saving 714 blobs and offsets to registry data/registry.dat
[2020-05-15T04:48:34,424][INFO ][logstash.inputs.azureblobstorage][nsg] nsg partial file resourceId=/SUBSCRIPTIONS/XXX.../BASTION-SG/y=2020/m=05/d=15/h=04/m=00/macAddress=XXXXXXXEF06/PT1H.json from 78487 to 80052
[2020-05-15T04:48:34,428][INFO ][logstash.inputs.azureblobstorage][nsg] nsg processed 2580 events, saving 714 blobs and offsets to registry data/registry.dat
[2020-05-15T04:49:35,857][INFO ][logstash.inputs.azureblobstorage][nsg] nsg processed 3469 events, saving 714 blobs and offsets to registry data/registry.dat
`

But when I see the local file in logstash, it just write the 20200514's data....
there are noting in 2020/05/15

Below is my pipeline:
`
input {
    azure_blob_storage {
        storageaccount => "xxxxxxxxxx"
        access_key => "....."
        container => "insights-logs-networksecuritygroupflowevent"
        prefix => "resourceId=/"
        logtype => "nsgflowlog"
        codec => "json"
        interval => 30
    }
}
filter {
    json {
        source => "message"
    }
    if [rule] == "UserRule_allow_my_lb" or [dst_ip] in ["10.113.27.176", "10.18.112.36"] {
        drop { }
    }
    mutate {
        add_field => { "environment" => "test-env" }
    }
    date {
        match => ["unixtimestamp", "UNIX"]
        target => "@timestamp"
        timezone => "UTC"
    }
    if ![src_bytes] {
        mutate { coerce => { "[src_bytes]" => "0" } }
    }
    if ![dst_bytes] {
        mutate { coerce => { "[dst_bytes]" => "0" } }
    }
    if ![src_pack] {
        mutate { coerce => { "[src_pack]" => "0" } }
    }
    if ![dst_pack] {
        mutate { coerce => { "[dst_pack]" => "0" } }
    }
}
output {
    file {
        path => "/logarchive/networksecuritygroup/nsg_%{+YYYYMMdd}.log"
        codec => line {
            format => "%{@timestamp}|%{environment}|%{subscription}|%{resourcegroup}|%{nsg}|%{rule}|%{src_ip}|%{dst_ip}|%{src_port}|%{dst_port}|%{protocol}|%{direction}|%{decision}|%{flowstate}|%{src_pack}|%{src_bytes}|%{dst_pack}|%{dst_bytes}"
        }
    }
}
`

**Comment by janmg** [comment]
Do you have a Kibana and x-pack monitoring enabled? you don't need the x-pack license for that. It can show how much time is spent on average in every step of the pipeline. 

azure_blob_storage is the input plugin and if it states processed 2580 events it is processing the files and parsed the json. If you add debug_until => 10000 my plugin will show for the first 10000 events which file it read and than switch back to normal info logging.

I suspect the file output plugin to to write %{_YYYYMMdd} to be based on the current day and not on the date that the event actually happened.

**Comment by royoan** [comment]
date { 
  match => ["unixtimestamp", "UNIX"] 
  target => "@timestamp" 
  timezone => "UTC" 
} 
this filter plugn will assign the event time to @timestamp, and 
The variable %{YYYYMMdd} is from @timestamp, pls correct me if it's wrong

**Comment by janmg** [comment]
date processing happens in filter, this is an input plugin
